test_that("function works", {

  sim_data = simulate_data(seed = 1, n_basis = 10)

  y = sim_data$y
  id = sim_data$id
  time = sim_data$time

  K = 2
  G = 3
  M = 2
  n_basis = 10
  iters = 10
  burn_in = 0
  thin = 1
  chains = 2
  n_cores = 1
  mixscat_prior = FALSE
  alpha_prior = "normal"
  center_data = TRUE
  scale_data = TRUE
  init_list = NULL
  z = NULL
  w = NULL
  w_prior = NULL
  seed = NULL
  w_dirichlet = 0.01
  z_dirichlet = 0.01
  spline_intercept_penalty = 1
  spline_penalty = 1
  cusp_nu = 4
  cusp_a = 2
  cusp_b = 2
  cusp_min_var = 0.01
  cusp_adapt_H = FALSE
  cusp_alpha0 = -4
  cusp_alpha1 = -5*1e-3

  fit = fit_model(
    y = sim_data$y,
    id = sim_data$id,
    time = sim_data$time,
    K = 2,
    G = 3,
    M = 2,
    n_basis = 10,
    iters = 10,
    burn_in = 0,
    thin = 1,
    chains = 2,
    n_cores = 1,
    mixscat_prior = FALSE,
    alpha_prior = "normal",
    center_data = TRUE,
    scale_data = TRUE,
    init_list = NULL,
    z = NULL,
    w = NULL,
    w_prior = NULL,
    seed = NULL,
    w_dirichlet = 0.01,
    z_dirichlet = 0.01,
    spline_intercept_penalty = 1,
    spline_penalty = 1,
    cusp_nu = 4,
    cusp_a = 2,
    cusp_b = 2,
    cusp_min_var = 0.01,
    cusp_adapt_H = FALSE,
    cusp_alpha0 = -4,
    cusp_alpha1 = -5*1e-3
  ) %>% expect_no_error()

  # cusp
  fit = fit_model(
    y = sim_data$y,
    id = sim_data$id,
    time = sim_data$time,
    K = 10,
    G = 3,
    M = 2,
    n_basis = 10,
    iters = 10,
    burn_in = 0,
    thin = 1,
    chains = 2,
    n_cores = 1,
    mixscat_prior = FALSE,
    alpha_prior = "cusp",
    center_data = TRUE,
    scale_data = TRUE,
    init_list = NULL,
    z = NULL,
    w = NULL,
    w_prior = NULL,
    seed = NULL,
    w_dirichlet = 0.01,
    z_dirichlet = 0.01,
    spline_intercept_penalty = 1,
    spline_penalty = 1,
    cusp_nu = 4,
    cusp_a = 2,
    cusp_b = 2,
    cusp_min_var = 0.01,
    cusp_adapt_H = TRUE,
    cusp_alpha0 = -4,
    cusp_alpha1 = -5*1e-3
  ) %>% expect_no_error()

  # cusp
  fit = fit_model(
    y = sim_data$y,
    id = sim_data$id,
    time = sim_data$time,
    K = 10,
    G = 3,
    M = 2,
    n_basis = 10,
    iters = 10,
    burn_in = 0,
    thin = 1,
    chains = 2,
    n_cores = 1,
    mixscat_prior = FALSE,
    alpha_prior = "normal",
    center_data = TRUE,
    scale_data = TRUE,
    init_list = NULL,
    z = NULL,
    w = NULL,
    w_prior = NULL,
    seed = NULL,
    w_dirichlet = 0.01,
    z_dirichlet = 0.01,
    spline_intercept_penalty = 1,
    spline_penalty = 1,
    cusp_nu = 4,
    cusp_a = 2,
    cusp_b = 2,
    cusp_min_var = 0.01,
    cusp_adapt_H = TRUE,
    cusp_alpha0 = -4,
    cusp_alpha1 = -5*1e-3
  ) %>% expect_no_error()
})
