// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// propose_coef_rcpp
arma::vec propose_coef_rcpp(const arma::vec& y, const arma::mat& X, const arma::vec& y_prec, const arma::mat& X_prec, const arma::vec& prior_mean, const arma::mat& prior_precision);
RcppExport SEXP _mixff_propose_coef_rcpp(SEXP ySEXP, SEXP XSEXP, SEXP y_precSEXP, SEXP X_precSEXP, SEXP prior_meanSEXP, SEXP prior_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_prec(y_precSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_prec(X_precSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_precision(prior_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(propose_coef_rcpp(y, X, y_prec, X_prec, prior_mean, prior_precision));
    return rcpp_result_gen;
END_RCPP
}
// sample_theta_cpp
arma::mat sample_theta_cpp(const arma::mat& y, const arma::mat& alpha, const arma::mat& prior_mean, const arma::vec& psi, const bool center);
RcppExport SEXP _mixff_sample_theta_cpp(SEXP ySEXP, SEXP alphaSEXP, SEXP prior_meanSEXP, SEXP psiSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_theta_cpp(y, alpha, prior_mean, psi, center));
    return rcpp_result_gen;
END_RCPP
}
// sample_theta_i_cpp
arma::mat sample_theta_i_cpp(const arma::mat& y, const arma::mat& alpha, const arma::mat& prior_mean, const arma::mat& prior_precision, const arma::vec& psi);
RcppExport SEXP _mixff_sample_theta_i_cpp(SEXP ySEXP, SEXP alphaSEXP, SEXP prior_meanSEXP, SEXP prior_precisionSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_precision(prior_precisionSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_theta_i_cpp(y, alpha, prior_mean, prior_precision, psi));
    return rcpp_result_gen;
END_RCPP
}
// mvrnormArma
arma::mat mvrnormArma(int n, arma::vec mu, arma::mat sigma);
RcppExport SEXP _mixff_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_V
arma::mat cpp_compute_V(arma::mat X, arma::vec omega, arma::mat precision_matrix);
RcppExport SEXP _mixff_cpp_compute_V(SEXP XSEXP, SEXP omegaSEXP, SEXP precision_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision_matrix(precision_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_V(X, omega, precision_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_m
arma::mat cpp_compute_m(arma::mat V, arma::mat X, arma::vec z, arma::vec omega, arma::vec C);
RcppExport SEXP _mixff_cpp_compute_m(SEXP VSEXP, SEXP XSEXP, SEXP zSEXP, SEXP omegaSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_m(V, X, z, omega, C));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta
arma::mat sample_beta(arma::mat X, arma::vec omega, arma::mat inv_cov, arma::vec z, arma::vec C);
RcppExport SEXP _mixff_sample_beta(SEXP XSEXP, SEXP omegaSEXP, SEXP inv_covSEXP, SEXP zSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_cov(inv_covSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta(X, omega, inv_cov, z, C));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta2
arma::mat sample_beta2(arma::mat X, arma::vec omega, arma::mat precision_matrix, arma::vec z, arma::vec C);
RcppExport SEXP _mixff_sample_beta2(SEXP XSEXP, SEXP omegaSEXP, SEXP precision_matrixSEXP, SEXP zSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision_matrix(precision_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta2(X, omega, precision_matrix, z, C));
    return rcpp_result_gen;
END_RCPP
}
// logsumexp_cpp
double logsumexp_cpp(const arma::vec& x);
RcppExport SEXP _mixff_logsumexp_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// update_theta2_cpp
arma::mat update_theta2_cpp(arma::mat epsilon, Rcpp::List model_data);
RcppExport SEXP _mixff_update_theta2_cpp(SEXP epsilonSEXP, SEXP model_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type model_data(model_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta2_cpp(epsilon, model_data));
    return rcpp_result_gen;
END_RCPP
}
// post_epsilon_cpp
arma::mat post_epsilon_cpp(arma::mat prec_prior, arma::mat prec_data, arma::mat MU_scaled, arma::mat Rty_alpha_scaled);
RcppExport SEXP _mixff_post_epsilon_cpp(SEXP prec_priorSEXP, SEXP prec_dataSEXP, SEXP MU_scaledSEXP, SEXP Rty_alpha_scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type prec_prior(prec_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prec_data(prec_dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type MU_scaled(MU_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rty_alpha_scaled(Rty_alpha_scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(post_epsilon_cpp(prec_prior, prec_data, MU_scaled, Rty_alpha_scaled));
    return rcpp_result_gen;
END_RCPP
}
// utils_comp_epsilon
Rcpp::List utils_comp_epsilon(arma::mat& alpha, arma::mat& alpha_scaled_psi, arma::mat& RtR, arma::mat& Rty);
RcppExport SEXP _mixff_utils_comp_epsilon(SEXP alphaSEXP, SEXP alpha_scaled_psiSEXP, SEXP RtRSEXP, SEXP RtySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_scaled_psi(alpha_scaled_psiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type RtR(RtRSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Rty(RtySEXP);
    rcpp_result_gen = Rcpp::wrap(utils_comp_epsilon(alpha, alpha_scaled_psi, RtR, Rty));
    return rcpp_result_gen;
END_RCPP
}
// post_epsilon_cpp2
arma::vec post_epsilon_cpp2(const arma::mat& prec_prior, const arma::mat& prec_data, const arma::mat& MU_scaled, const arma::mat& Rty_alpha_scaled);
RcppExport SEXP _mixff_post_epsilon_cpp2(SEXP prec_priorSEXP, SEXP prec_dataSEXP, SEXP MU_scaledSEXP, SEXP Rty_alpha_scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type prec_prior(prec_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prec_data(prec_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type MU_scaled(MU_scaledSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Rty_alpha_scaled(Rty_alpha_scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(post_epsilon_cpp2(prec_prior, prec_data, MU_scaled, Rty_alpha_scaled));
    return rcpp_result_gen;
END_RCPP
}
// update_epsilon_cpp
arma::mat update_epsilon_cpp(arma::mat& alpha, arma::mat& alpha_scaled_psi, arma::mat& RtR, arma::mat& Rty, arma::mat& MU_scaled, arma::vec& inv_sigma, arma::uvec& z, arma::umat& idx);
RcppExport SEXP _mixff_update_epsilon_cpp(SEXP alphaSEXP, SEXP alpha_scaled_psiSEXP, SEXP RtRSEXP, SEXP RtySEXP, SEXP MU_scaledSEXP, SEXP inv_sigmaSEXP, SEXP zSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_scaled_psi(alpha_scaled_psiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type RtR(RtRSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Rty(RtySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type MU_scaled(MU_scaledSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type inv_sigma(inv_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(update_epsilon_cpp(alpha, alpha_scaled_psi, RtR, Rty, MU_scaled, inv_sigma, z, idx));
    return rcpp_result_gen;
END_RCPP
}
// update_epsilon_cpp_fast
arma::mat update_epsilon_cpp_fast(arma::mat& alpha, arma::mat& alpha_scaled_psi, arma::mat& RtR, arma::mat& Rty, arma::mat& MU_scaled, arma::vec& inv_sigma, arma::uvec& z, arma::umat& idx);
RcppExport SEXP _mixff_update_epsilon_cpp_fast(SEXP alphaSEXP, SEXP alpha_scaled_psiSEXP, SEXP RtRSEXP, SEXP RtySEXP, SEXP MU_scaledSEXP, SEXP inv_sigmaSEXP, SEXP zSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_scaled_psi(alpha_scaled_psiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type RtR(RtRSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Rty(RtySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type MU_scaled(MU_scaledSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type inv_sigma(inv_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(update_epsilon_cpp_fast(alpha, alpha_scaled_psi, RtR, Rty, MU_scaled, inv_sigma, z, idx));
    return rcpp_result_gen;
END_RCPP
}
// fast_dummy_dense
arma::mat fast_dummy_dense(arma::ivec x, int G);
RcppExport SEXP _mixff_fast_dummy_dense(SEXP xSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dummy_dense(x, G));
    return rcpp_result_gen;
END_RCPP
}
// compute_prob_group
arma::mat compute_prob_group(arma::mat& B, arma::mat& beta_group, arma::uvec& idx);
RcppExport SEXP _mixff_compute_prob_group(SEXP BSEXP, SEXP beta_groupSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta_group(beta_groupSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_prob_group(B, beta_group, idx));
    return rcpp_result_gen;
END_RCPP
}
// predict_prob_cpp
arma::mat predict_prob_cpp(int& M, arma::ivec& w, arma::mat& B, arma::mat& beta);
RcppExport SEXP _mixff_predict_prob_cpp(SEXP MSEXP, SEXP wSEXP, SEXP BSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_prob_cpp(M, w, B, beta));
    return rcpp_result_gen;
END_RCPP
}
// fast_aggregate_sum
arma::vec fast_aggregate_sum(arma::vec& log_pz, arma::ivec& id);
RcppExport SEXP _mixff_fast_aggregate_sum(SEXP log_pzSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type log_pz(log_pzSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_aggregate_sum(log_pz, id));
    return rcpp_result_gen;
END_RCPP
}
// update_theta_cpp
arma::mat update_theta_cpp(const arma::mat& epsilon, const arma::mat& R, const arma::vec& id, const arma::vec& id_unique);
RcppExport SEXP _mixff_update_theta_cpp(SEXP epsilonSEXP, SEXP RSEXP, SEXP idSEXP, SEXP id_uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type id_unique(id_uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta_cpp(epsilon, R, id, id_unique));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixff_propose_coef_rcpp", (DL_FUNC) &_mixff_propose_coef_rcpp, 6},
    {"_mixff_sample_theta_cpp", (DL_FUNC) &_mixff_sample_theta_cpp, 5},
    {"_mixff_sample_theta_i_cpp", (DL_FUNC) &_mixff_sample_theta_i_cpp, 5},
    {"_mixff_mvrnormArma", (DL_FUNC) &_mixff_mvrnormArma, 3},
    {"_mixff_cpp_compute_V", (DL_FUNC) &_mixff_cpp_compute_V, 3},
    {"_mixff_cpp_compute_m", (DL_FUNC) &_mixff_cpp_compute_m, 5},
    {"_mixff_sample_beta", (DL_FUNC) &_mixff_sample_beta, 5},
    {"_mixff_sample_beta2", (DL_FUNC) &_mixff_sample_beta2, 5},
    {"_mixff_logsumexp_cpp", (DL_FUNC) &_mixff_logsumexp_cpp, 1},
    {"_mixff_update_theta2_cpp", (DL_FUNC) &_mixff_update_theta2_cpp, 2},
    {"_mixff_post_epsilon_cpp", (DL_FUNC) &_mixff_post_epsilon_cpp, 4},
    {"_mixff_utils_comp_epsilon", (DL_FUNC) &_mixff_utils_comp_epsilon, 4},
    {"_mixff_post_epsilon_cpp2", (DL_FUNC) &_mixff_post_epsilon_cpp2, 4},
    {"_mixff_update_epsilon_cpp", (DL_FUNC) &_mixff_update_epsilon_cpp, 8},
    {"_mixff_update_epsilon_cpp_fast", (DL_FUNC) &_mixff_update_epsilon_cpp_fast, 8},
    {"_mixff_fast_dummy_dense", (DL_FUNC) &_mixff_fast_dummy_dense, 2},
    {"_mixff_compute_prob_group", (DL_FUNC) &_mixff_compute_prob_group, 3},
    {"_mixff_predict_prob_cpp", (DL_FUNC) &_mixff_predict_prob_cpp, 4},
    {"_mixff_fast_aggregate_sum", (DL_FUNC) &_mixff_fast_aggregate_sum, 2},
    {"_mixff_update_theta_cpp", (DL_FUNC) &_mixff_update_theta_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
