// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// propose_coef_rcpp
arma::vec propose_coef_rcpp(const arma::vec& y, const arma::mat& X, const arma::vec& y_prec, const arma::mat& X_prec, const arma::vec& prior_mean, const arma::mat& prior_precision);
RcppExport SEXP _mixff_propose_coef_rcpp(SEXP ySEXP, SEXP XSEXP, SEXP y_precSEXP, SEXP X_precSEXP, SEXP prior_meanSEXP, SEXP prior_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_prec(y_precSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_prec(X_precSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_precision(prior_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(propose_coef_rcpp(y, X, y_prec, X_prec, prior_mean, prior_precision));
    return rcpp_result_gen;
END_RCPP
}
// sample_theta_cpp
arma::mat sample_theta_cpp(const arma::mat& y, const arma::mat& alpha, const arma::mat& prior_mean, const arma::vec& psi, const bool center);
RcppExport SEXP _mixff_sample_theta_cpp(SEXP ySEXP, SEXP alphaSEXP, SEXP prior_meanSEXP, SEXP psiSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_theta_cpp(y, alpha, prior_mean, psi, center));
    return rcpp_result_gen;
END_RCPP
}
// sample_theta_i_cpp
arma::mat sample_theta_i_cpp(const arma::mat& y, const arma::mat& alpha, const arma::mat& prior_mean, const arma::mat& prior_precision, const arma::vec& psi);
RcppExport SEXP _mixff_sample_theta_i_cpp(SEXP ySEXP, SEXP alphaSEXP, SEXP prior_meanSEXP, SEXP prior_precisionSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_precision(prior_precisionSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_theta_i_cpp(y, alpha, prior_mean, prior_precision, psi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_V
arma::mat cpp_compute_V(arma::mat X, arma::vec omega, arma::mat inv_cov);
RcppExport SEXP _mixff_cpp_compute_V(SEXP XSEXP, SEXP omegaSEXP, SEXP inv_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_cov(inv_covSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_V(X, omega, inv_cov));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_m
arma::mat cpp_compute_m(arma::mat V, arma::mat X, arma::vec z, arma::vec omega, arma::vec C, arma::vec center, arma::mat inv_cov);
RcppExport SEXP _mixff_cpp_compute_m(SEXP VSEXP, SEXP XSEXP, SEXP zSEXP, SEXP omegaSEXP, SEXP CSEXP, SEXP centerSEXP, SEXP inv_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type center(centerSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_cov(inv_covSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_m(V, X, z, omega, C, center, inv_cov));
    return rcpp_result_gen;
END_RCPP
}
// mvrnormArma
arma::mat mvrnormArma(int n, arma::vec mu, arma::mat sigma);
RcppExport SEXP _mixff_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta
arma::mat sample_beta(arma::mat X, arma::vec omega, arma::mat inv_cov, arma::vec z, arma::vec C, arma::vec center);
RcppExport SEXP _mixff_sample_beta(SEXP XSEXP, SEXP omegaSEXP, SEXP inv_covSEXP, SEXP zSEXP, SEXP CSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_cov(inv_covSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta(X, omega, inv_cov, z, C, center));
    return rcpp_result_gen;
END_RCPP
}
// logsumexp_cpp
double logsumexp_cpp(const arma::vec& x);
RcppExport SEXP _mixff_logsumexp_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixff_propose_coef_rcpp", (DL_FUNC) &_mixff_propose_coef_rcpp, 6},
    {"_mixff_sample_theta_cpp", (DL_FUNC) &_mixff_sample_theta_cpp, 5},
    {"_mixff_sample_theta_i_cpp", (DL_FUNC) &_mixff_sample_theta_i_cpp, 5},
    {"_mixff_cpp_compute_V", (DL_FUNC) &_mixff_cpp_compute_V, 3},
    {"_mixff_cpp_compute_m", (DL_FUNC) &_mixff_cpp_compute_m, 7},
    {"_mixff_mvrnormArma", (DL_FUNC) &_mixff_mvrnormArma, 3},
    {"_mixff_sample_beta", (DL_FUNC) &_mixff_sample_beta, 6},
    {"_mixff_logsumexp_cpp", (DL_FUNC) &_mixff_logsumexp_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
