# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

propose_coef_rcpp <- function(y, X, y_prec, X_prec, prior_mean, prior_precision) {
    .Call(`_mixff_propose_coef_rcpp`, y, X, y_prec, X_prec, prior_mean, prior_precision)
}

sample_theta_cpp <- function(y, alpha, prior_mean, psi, center) {
    .Call(`_mixff_sample_theta_cpp`, y, alpha, prior_mean, psi, center)
}

sample_theta_i_cpp <- function(y, alpha, prior_mean, prior_precision, psi) {
    .Call(`_mixff_sample_theta_i_cpp`, y, alpha, prior_mean, prior_precision, psi)
}

cpp_compute_V <- function(X, omega, inv_cov) {
    .Call(`_mixff_cpp_compute_V`, X, omega, inv_cov)
}

cpp_compute_m <- function(V, X, z, omega, C, center, inv_cov) {
    .Call(`_mixff_cpp_compute_m`, V, X, z, omega, C, center, inv_cov)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_mixff_mvrnormArma`, n, mu, sigma)
}

sample_beta <- function(X, omega, inv_cov, z, C, center) {
    .Call(`_mixff_sample_beta`, X, omega, inv_cov, z, C, center)
}

logsumexp_cpp <- function(x) {
    .Call(`_mixff_logsumexp_cpp`, x)
}

